name: drones
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libavif_api=1.3.0
  - absl-py=2.1.0
  - annotated-types=0.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.2.25
  - cairo=1.18.4
  - certifi=2026.2.25
  - charset-normalizer=3.3.2
  - click=8.3.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - dav1d=1.2.1
  - docker-pycreds=0.4.0
  - eval_type_backport=0.3.1
  - farama-notifications=0.0.4
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.46
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - grpcio=1.74.1
  - gymnasium=1.0.0
  - harfbuzz=10.4.0
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250512.1
  - libavif=1.3.0
  - libavif16=1.3.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.84.0
  - libgrpc=1.74.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=2.0.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown=3.6
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.5.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.4.2
  - numpy-base=2.0.1
  - onnx=1.20.0
  - openjpeg=2.5.2
  - openssl=3.6.1
  - packaging=24.2
  - pcre2=10.44
  - pip=24.2
  - pixman=0.46.4
  - platformdirs=4.9.4
  - psutil=7.2.2
  - pydantic=2.11.10
  - pydantic-core=2.33.2
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - rav1e=0.7.1
  - re2=2025.11.05
  - requests=2.32.3
  - scipy=1.15.1
  - sentry-sdk=2.54.0
  - setproctitle=1.3.7
  - setuptools=75.1.0
  - six=1.17.0
  - smmap=5.0.2
  - sqlite=3.45.3
  - svt-av1=3.1.2
  - tbb=2021.8.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.13
  - tqdm=4.67.3
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.2
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - urllib3=2.3.0
  - vc=14.40
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wandb=0.25.0
  - werkzeug=3.1.3
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xz=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - etils==1.13.0
      - flatbuffers==25.12.19
      - fonttools==4.55.5
      - fsspec==2026.3.0
      - glfw==2.10.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - humanfriendly==10.0
      - importlib-resources==7.1.0
      - kiwisolver==1.4.8
      - markdown-it-py==4.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mujoco==3.8.0
      - numpy==2.2.2
      - onnx-simplifier==0.4.36
      - onnxruntime==1.23.2
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==5.29.3
      - pybullet==3.2.6
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.2.1
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - rich==14.2.0
      - seaborn==0.13.2
      - sympy==1.13.1
      - tensorboardx==2.6.2.2
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tzdata==2025.1
